/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for our documentation
  docs: [
    {
      type: 'category',
      label: 'Module 1: ROS 2 Middleware',
      items: [
        'module1/introduction',
        'module1/chapter1',
        'module1/chapter2',
        'module1/chapter3'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['tutorial-basics/congratulations'],
    },
  ],
};
